### ISSUE TITLE
[1.8.1 Spigot] Crash at server start up.

### ISSUE THREAD

**Issue by Capsar** [viperMonster/Soups#1]
Crash log:
![ss 2015-02-16 at 06 52 07](https://cloud.githubusercontent.com/assets/10345197/6216733/eb2aa618-b60c-11e4-9195-a72959280fe8.png)

The error could be caused by the fact that I am running the server on 1.8.1 But since it said there was no Vault I still wanted to report it.. Thanks for looking into it

Keep up the greate work!

**Comment by viperMonster** [comment]
Thanks for the report, I'll fix this immediately.

**Comment by viperMonster** [comment]
This should fix it. [fa6a471](https://github.com/viperMonster/Soups/commit/fa6a4717774d8c768016edb47e7f20c825cda268)

**Comment by viperMonster** [comment]
You can temporary download it [here] (https://mega.co.nz/#!4RZTxCRS!gn9hOGNILy7WqkY2Kuch0FhHY-feiNq3PUshC67n92M)
